source 'https://github.com/CocoaPods/Specs.git'
source 'https://a64289a751529c25114b3e4f3f02f0960c1048e1@github.vodafone.com/TSS-MyVodafone-CoreApp/iOS-CocoaPods.git'


# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'My Vodafone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~> 4.0'
  pod 'FSPagerView'
  pod 'CryptoSwift'
  pod 'VFGSplash', '2.0.7'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for My Vodafone

end
